### ISSUE TITLE
TypeError: e._legacySignMessage is not a function

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#1767]
When trying to use ocean.js-cli with barge, I found this:
```
alx@ubuntu:/ocean/ocean.js-cli$ npm run cli startCompute did:op:f1a4a17ed223bbfc4f50751cf891c910e6c9753d8b086d6f18c951e661d62679 did:op:5e9abfdcf180dd1de81157838fecb3cd558f005204558544a924225e0e936ca9

> ocean-demo@2.0.0 cli
> ./node_modules/ts-node/dist/bin.js src/index.ts "startCompute" "did:op:f1a4a17ed223bbfc4f50751cf891c910e6c9753d8b086d6f18c951e661d62679" "did:op:5e9abfdcf180dd1de81157838fecb3cd558f005204558544a924225e0e936ca9"

Using account: 0xe2DD09d719Da89e5a3D0F2549c7E24566e947260
Using metadataCache : http://172.15.0.5:5000
Using Provider : http://172.15.0.4:8030
{
  chainId: 8996,
  network: 'development',
  metadataCacheUri: 'http://172.15.0.5:5000',
  nodeUri: 'http://127.0.0.1:8545',
  providerUri: 'http://172.15.0.4:8030',
  subgraphUri: 'https://172.15.0.15:8000',
  explorerUri: null,
  oceanTokenAddress: '0x2473f4F7bf40ed9310838edFCA6262C17A59DF64',
  oceanTokenSymbol: 'OCEAN',
  fixedRateExchangeAddress: '0xBb0911124E680D65358Ac46C5404D4dF01F03e80',
  dispenserAddress: '0xe749E2f8482810b11B838Ae8c5eb69e54d610411',
  startBlock: 5,
  transactionBlockTimeout: 50,
  transactionConfirmationBlocks: 1,
  transactionPollingTimeout: 750,
  gasFeeMultiplier: 1,
  nftFactoryAddress: '0x8930D1F61Defb9CBD652136B4C3D93f19AC35678',
  opfCommunityFeeCollector: '0x2fC1fd21cb222Dc180Ef817dE4c426fd9230b5A5',
  veAllocate: '0x726baA2f854A3BEC2378a707AeB38c9d933Ebad6',
  veOCEAN: '0xc354ba9AD5dF1023C2640b14A09E61a500F21546',
  veDelegation: '0xF152cF3c67dFD41a317eAe8fAc0e1e8E98724A13',
  veFeeDistributor: '0x336EFb3c9E56F713dFdA4CDB3Dd0882F3226b6eE',
  veDelegationProxy: '0xfeA10BBb093d7fcb1EDf575Aa7e28d37b9DcFcE9',
  DFRewards: '0x8F006DbB3727d18f032C5618595ecDD2EDE13b61',
  DFStrategyV1: '0x19513460bc16254c74AE806683E906478A42B543',
  veFeeEstimate: '0xEEE56e2a630DD29F9A628d618E58bb173911F393'
}
[getNonce] Consumer: 0xe2DD09d719Da89e5a3D0F2549c7E24566e947260 nonce: 1
/ocean/ocean.js-cli/node_modules/@oceanprotocol/lib/src/services/Provider.ts:130
      return await (signer as providers.JsonRpcSigner)._legacySignMessage(
                                                       ^
TypeError: e._legacySignMessage is not a function
    at messageHashBytes (/ocean/ocean.js-cli/node_modules/@oceanprotocol/lib/src/services/Provider.ts:130:56)
    at /ocean/ocean.js-cli/node_modules/@oceanprotocol/lib/src/services/Provider.ts:131:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by bogdanfazakas** [comment]
closed by #1772
