### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean.js#753]
It looks the Ocean.js isn't being built correctly when it's used with Ocean sub graph:

```
 Error: Cannot find module '/home/runner/work/ocean-subgraph/ocean-subgraph/node_modules/@oceanprotocol/lib/dist/lib.modern.js'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:907:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:900:15)
    at resolveExports (internal/modules/cjs/loader.js:432:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/runner/work/ocean-subgraph/ocean-subgraph/test/integration/Datatokens.test.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/home/runner/work/ocean-subgraph/ocean-subgraph/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/home/runner/work/ocean-subgraph/ocean-subgraph/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.exports.requireOrImport (/home/runner/work/ocean-subgraph/ocean-subgraph/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/home/runner/work/ocean-subgraph/ocean-subgraph/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/home/runner/work/ocean-subgraph/ocean-subgraph/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/home/runner/work/ocean-subgraph/ocean-subgraph/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/home/runner/work/ocean-subgraph/ocean-subgraph/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/home/runner/work/ocean-subgraph/ocean-subgraph/node_modules/mocha/lib/cli/run.js:362:11)
    at /home/runner/work/ocean-subgraph/ocean-subgraph/node_modules/yargs/build/index.cjs:443:71
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ocean-subgraph@1.1.1 test-integration: `TS_NODE_PROJECT='test/integration/tsconfig.json' mocha --config=test/integration/.mocharc.json --node-env=test --exit 'test/integration/**/*.test.ts'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ocean-subgraph@1.1.1 test-integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-19T01_07_27_888Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by jamiehewitt15** [comment]
Full build logs: https://github.com/oceanprotocol/ocean-subgraph/runs/2376793860?check_suite_focus=true

**Comment by alexcos20** [comment]
In ocean-subgraph, it's standard ocean.js usage:
- https://github.com/oceanprotocol/ocean-subgraph/blob/main/package.json#L56
- https://github.com/oceanprotocol/ocean-subgraph/blob/main/test/integration/Datatokens.test.ts#L5

**Comment by jamiehewitt15** [comment]
I think the issue could be caused by the wrong name in the "exports" field within package.json: https://github.com/oceanprotocol/ocean.js/pull/754/files

**Comment by jamiehewitt15** [comment]
I re-ran the build job in the Ocean Sub Graph and it's still giving the same error: https://github.com/oceanprotocol/ocean-subgraph/runs/2380269955?check_suite_focus=true

**Comment by alexcos20** [comment]
We need to release a new ocean.js first and bump it in subgraph.  Doing that now

**Comment by jamiehewitt15** [comment]
Ok cool, thank you

**Comment by alexcos20** [comment]
https://github.com/oceanprotocol/ocean-subgraph/pull/89/checks?check_run_id=2381209889

**Comment by alexcos20** [comment]
if it helps @jamiehewitt15 👍 

/ocean/ocean-subgraph$ ls node_modules/@oceanprotocol/lib/dist/node/
balancer/                   exchange/                   lib.d.ts                    lib.module.js               lib.umd.js.map              ocean/
datatokens/                 index.d.ts                  lib.js                      lib.module.js.map           metadatacache/              provider/
ddo/                        Instantiable.abstract.d.ts  lib.js.map                  lib.umd.js                  models/                     utils/

I can see lib.module.js  in node_modules/@oceanprotocol/lib/dist/node/ and not in node_modules/@oceanprotocol/lib/dist/

**Comment by jamiehewitt15** [comment]
@alexcos20 Thank you for pointing that out. I have updated the paths here: https://github.com/oceanprotocol/ocean.js/pull/756/files

**Comment by alexcos20** [comment]
and still fails:  https://github.com/oceanprotocol/ocean-subgraph/pull/89/checks?check_run_id=2382858822
this time with another error

**Comment by jamiehewitt15** [comment]
This is what I was suggesting on the calling, potentially trying to use the Common JS bundle rather than the ESM module: https://github.com/oceanprotocol/ocean.js/pull/761/files

I'll try and test it locally with Ocean sub graph

**Comment by jamiehewitt15** [comment]
@alexcos20 I tested out pull request #761 with Ocean sub graph using `npm link` and the integration tests passed
